locator:
  url: https://bcl.difi.blufo.net/

issuers:
  certificate:
    - https://certpub.com/provider/buypass/production-root.crt
    - https://certpub.com/provider/buypass/production.crt
    - https://certpub.com/provider/commfides/production-root.crt
    - https://certpub.com/provider/commfides/production.crt