locator:
  url: https://test-bcl.difi.blufo.net/

issuers:
  certificate:
    - https://certpub.com/provider/buypass/test.crt
    - https://certpub.com/provider/commfides/test.crt
    - https://certpub.com/provider/commfides/test2.crt