spec:
  locator:
    - id: certpub-v1
      name: CertPub Locator v1
      impl: CertPub::Spec::LocatorV1

  publisher:
    - id: certpub-encryption-v1
      key: difi-bcp-v1
      name: CertPub Publisher v1, encryption
      impl: CertPub::Spec::PublisherV1Encryption

    - id: certpub-signing-v1
      key: difi-bcp-v1
      name: CertPub Publisher v1, signing
      impl: CertPub::Spec::PublisherV1Signing
  